name: Deploy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Dokku server
        uses: dokku/github-action@v1.0.1
        with:
          branch: main
          git_remote_url: "ssh://dokku@gcies.noxt.us:14422/openis"
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
